version: '3'
services:
    php:
        # image: 'php:8.1-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: php
        restart: unless-stopped
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mariadb

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        restart: unless-stopped
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.4
        container_name: mariadb
        restart: unless-stopped
        #ports:
        #    - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
            - mariadb-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=0
            - PMA_HOST=mariadb
        restart: unless-stopped
        depends_on:
            - mariadb
volumes:
    mariadb-data: